package LaunchFunction.DataConvert;

public interface Converter {

    // Load data files generated by jgitrepo module to memory.
    public int readOriginalFile(String path);

    // convert original data to sql format. The sql variables should be fields of “ConverterImpl”.
    public void convert();

    // preparing data, then call api in jdbc module to insert data to database.
    public int insertToSQL();
}
