package LaunchFunction.DataConvert;

import dataconvert.model.DBTable;

public class ExampleConverterImpl implements Converter {

    // original data should also be a field of Converter.
    // This kinds of structure can be optimized by stream process.
    DBTable target_table = new DBTable();


    public int readOriginalFile(String path) {

        // TODO: Load data files generated by jgitrepo module to memory.                                                                                                                                                                                  

        return 0;
    }

    public void convert() {

        // TODO: convert original data to sql format. The sql variables should be fields of “ConverterImpl“.

    }

    public int insertToSQL() {

        // TODO: preparing data, then call api in jdbc module to insert data to database.

        return 0;
    }

}
